### ISSUE TITLE
Unexpected token '?'

### ISSUE THREAD

**Issue by jrock2004** [empress/ember-showdown-prism#11] opened 2020-08-26 17:20 UTC
Just installed your addon, and now when I run the ember app and visit localhost:4200 if it does build, I get the following

```
/var/folders/ml/v_kkd18n5tx7kqd73pwxszq8kgd__9/T/broccoli-14454EqySJH9Y5yYh/out-497-broccoli_merge_trees/assets/vendor.js:110196
      return this.args.language ?? 'markup';
                                 ^

SyntaxError: Unexpected token '?'
    at new Script (vm.js:88:7)
    at VMSandbox.eval (/Users/john.costanzo/Development/website/node_modules/fastboot/src/vm-sandbox.js:13:22)
    at /Users/john.costanzo/Development/website/node_modules/fastboot/src/ember-app.js:190:15
    at Array.forEach (<anonymous>)
    at EmberApp.loadAppFiles (/Users/john.costanzo/Development/website/node_modules/fastboot/src/ember-app.js:187:21)
    at EmberApp.retrieveSandboxedApp (/Users/john.costanzo/Development/website/node_modules/fastboot/src/ember-app.js:235:10)
    at new EmberApp (/Users/john.costanzo/Development/website/node_modules/fastboot/src/ember-app.js:61:21)
    at FastBoot._buildEmberApp (/Users/john.costanzo/Development/website/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/Users/john.costanzo/Development/website/node_modules/fastboot/src/index.js:52:10)
    at /Users/john.costanzo/Development/website/node_modules/ember-cli-fastboot/index.js:335:29
```

If I remove this addon, remove node modules and redo npm install and start the app, it runs just fine

**Comment by mansona** [comment] 2020-08-26 19:56
Hey @jrock2004 👋 the issue is because of an issue that I'm trying to resolve in https://github.com/ember-fastboot/ember-cli-fastboot/pull/770 

Essentially you need to add `node: 'current'` to your targets in the `config/targets.js` file so that it looks like this at the bottom: 

```javascript
module.exports = {
  browsers,
  node: 'current'
};
```

This is absolutely not something that anyone should need to do manually, which is why I'm trying to get it fixed by default upstream 🙈

**Comment by jrock2004** [comment] 2020-08-26 20:55
That did the trick for me. I guess we can close this for now since it now works

**Closed as completed** 2020-08-26 21:11 UTC

**Comment by knownasilya** [comment] 2020-09-19 21:42
Just ran into this as well.
